# Generated by Django 4.2.1 on 2023-06-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='home/mix/myworldCopy/my_tennis_club/productionfiles/photos/'),
        ),
    ]
